/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        cream: "#FFF9F3",
        ink: "#2B2735",
        secondary: "#6B6577",
        muted: "#9A93A5",
        faint: "#B7B0C0",
        hairline: "#F1E7DB",
        card: "#FFFFFF",
        orange: "#FF7E1D",
        "orange-dark": "#C4560A",
        "orange-tint": "#FFEEDD",
        amber: "#FFD9B3",
        "amber-strong": "#FFC93E",
        "amber-tint": "#FFF3D2",
        "amber-ink": "#8A6A0E",
        sky: "#E3EDFF",
        "sky-strong": "#3B76F6",
        "sky-ink": "#2A57C4",
        lilac: "#EDEAFE",
        "lilac-strong": "#8A7CF0",
        "lilac-ink": "#5B4BC4",
        sage: "#DDF5EF",
        "sage-strong": "#12B392",
        "sage-ink": "#0E8E75",
        coral: "#FFE3E0",
        "coral-ink": "#B4523F",
      },
      fontFamily: {
        heading: ["Outfit_600SemiBold"],
        "heading-bold": ["Outfit_700Bold"],
        "heading-black": ["Outfit_800ExtraBold"],
        body: ["Nunito_400Regular"],
        "body-semi": ["Nunito_600SemiBold"],
        "body-bold": ["Nunito_700Bold"],
        "body-black": ["Nunito_800ExtraBold"],
      },
    },
  },
  plugins: [],
};
